embedding_size: 64
weight_size: [64, 64]
n_layers: 3
reg_weight: 1e-4

pretrain_epochs: 10
pretrain_lr: 0.001
pretrain_layers: [3]
pretrain_decay: 0.0001
pretrain_keep_prob: 0.7

distill_layers: [1, 3]
distill_userK: 5
distill_itemK: 7
distill_thres: [0.3, 0.5]

distill_uuK: [3]

distill_iiK: [3, 5]
uuii_thres: [-1]

sim_mode: "cosine"
uu_lambda: [50, 100, 200]

ii_lambda: [50, 100, 200]

hyper_parameters: ["pretrain_layers", "distill_layers", "distill_thres", "distill_uuK", "distill_iiK", "uuii_thres", "uu_lambda", "ii_lambda"]