embedding_size: 64
n_ui_layers: [3]
n_layers: 1

learning_rate_scheduler: [0.96, 50]
lambda_coeff: 0.9
reg_weight: [1e-4]
#reg_weight: [1e-5,1e-4]
learning_rate: 0.001

cl_loss: 0.01 
temperature: 0.2
image_knn_k: [20]
#image_knn_k: [10,20]
text_knn_k: [20]
#text_knn_k: [10,20]

dropout_rate : [0.1]
#dropout_rate : [0, 0.1]

hyper_parameters: ["n_ui_layers", "image_knn_k", "text_knn_k", "reg_weight", "dropout_rate"]